//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REST_XMLRPC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contents()
        {
            this.Subscriptions = new HashSet<Subscriptions>();
        }
    
        public int Id { get; set; }
        public int TopicsId { get; set; }
        public int ContentTypeId { get; set; }
        public double Price { get; set; }
        public string Data { get; set; }
    
        public virtual ContentTypes ContentTypes { get; set; }
        public virtual Topics Topics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscriptions> Subscriptions { get; set; }
    }
}
