//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriptions
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ContentId { get; set; }
    
        public virtual Contents Contents { get; set; }
        public virtual Users Users { get; set; }
    }
}
